News list screen
mmmnmnm/lahmacun_rework pull request #207
Opened 2021-12-24 14:44 UTC by gygabor

2021-12-25 09:17 UTC, baxgas requested changes
Thank you for the huge work with the List pages! 
A few things to change and fix:
- archive search is still buggy, gives the old links/slugs to the updated search list -> please fix
- the news/tags page should use the same template/component as the main news page -> please fix
- the shows/archive list and the news list pages use a bit different design, which is ok to me, since they are different content-wise. 
but, shows/archive have 4 items, news have 3 in a row -> I think we should use 3 for both (larger), maybe have an extra breakpoint for very large screens showing 4. 
small mistake: shows items have rounded corners, Csenge noted these shouldn't be rounded, can you fix please?
- _bonus_ (if you want to make it in this round), the opening page Latest Arcsi Episodes could use the same items template as the Archive page
- _question_: in what does the Archive search search in? I think it should be improved, it doesn't give me much meaningful results, I think the search should look in Show title, Episode title and Episode description. 
At the end it will be done via arcsi API calls but, who knows when it will be available, so maybe it is worth improving with this method

2021-12-25 11:17 UTC, gygabor commented
> Thank you for the huge work with the List pages! A few things to change and fix:
> 
> * archive search is still buggy, gives the old links/slugs to the updated search list -> please fix
>   archive page should also have the same Load more bubble as the News...
> * the news/tags page should use the same template/component as the main news page -> please fix
> * the shows/archive list and the news list pages use a bit different design, which is ok to me, since they are different content-wise.
>   but, shows/archive have 4 items, news have 3 in a row -> I think we should use 3 for both (larger), maybe have an extra breakpoint for very large screens showing 4.
>   small mistake: shows items have rounded corners, Csenge noted these shouldn't be rounded, can you fix please?
> * _bonus_ (if you want to make it in this round), the opening page Latest Arcsi Episodes could use the same items template as the Archive page
> * _question_: in what does the Archive search search in? I think it should be improved, it doesn't give me much meaningful results, I think the search should look in Show title, Episode title and Episode description.
>   At the end it will be done via arcsi API calls but, who knows when it will be available, so maybe it is worth improving with this method

I didn't update the other pages on purpose. This PR only affects the `news` page. I don't want to open a huge monster PR. If you approve it then I update other list alike pages. I thought it's a better approach than revert every component if you find some issue or disagree with my solution.  After it, the shows list will use the same item block. As I remember we agreed every list should look like the `news` page in this PR.
I think the search fix on `archive` is out of scope. But I can check it.

2021-12-25 11:18 UTC, gygabor commented on app/pages/news/tags/_tag.vue
>      <div class="container mt-8">
This PR only affects the news page. If you approve it then I update other list alike pages.

2021-12-25 11:20 UTC, gygabor commented on app/assets/css/globalstyles.scss
> +*:hover {
It was a sudden idea. I found it would be nice the hover effect. Let's see how it works.

2021-12-25 12:11 UTC, gygabor commented on app/pages/archive.vue
>          <AutoCompleteSearch
I think it is out of the scope of this PR. I can fix it but if you approve this PR I'll update it anyway.

2021-12-26 09:35 UTC, baxgas approved these changes

2021-12-26 09:35 UTC, merged